markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Monica Dinosaurescu
url: http://www.google.com
description: A fantastic blog that is fantastic.
twitter: notwaldorf
github: notwaldorf
gravatar_url: /images/panda.jpg