markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
permalink: /posts/:title/
gems:
  - jemoji

name: Monica Dinculescu
url: http://meowni.ca
description: A wild blog appears.
future: true
twitter: notwaldorf
gravatar_url: https://s.gravatar.com/avatar/053e75a5b48b44d6dd0612795dfb326d
google_analytics_tracking_id: UA-47334320-2
