markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Monica Dinculescu
url: http://notwaldorf.github.io
description: A wild blog appears.
twitter: notwaldorf
gravatar_url: https://s.gravatar.com/avatar/053e75a5b48b44d6dd0612795dfb326d
google_analytics_tracking_id: UA-47334320-2
