markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Monica
url: http://notwaldorf.github.io
description: A wild blog appears.
twitter: notwaldorf
github: notwaldorf
gravatar_url: /images/panda.jpg
google_analytics_tracking_id: UA-47334320-2

